# --- STAGE 1: BUILD ---
FROM node:18-alpine as build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

COPY . .

RUN VITE_API_URL=http://3.225.220.112:8080/api npm run build

# --- STAGE 2: RUN (Nginx) ---
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]